export const Fruits = [
  { id: 1, name: "Apple", value: "apple" },
  { id: 2, name: "Banana", value: "banana" },
  { id: 3, name: "Mango", value: "mango" },
  { id: 4, name: "Orange", value: "orange" },
  { id: 5, name: "Grapes", value: "grapes" },
  { id: 6, name: "Pineapple", value: "pineapple" },
  { id: 7, name: "Papaya", value: "papaya" },
  { id: 8, name: "Strawberry", value: "strawberry" },
  { id: 9, name: "Blueberry", value: "blueberry" },
  { id: 10, name: "Blackberry", value: "blackberry" },
  { id: 11, name: "Watermelon", value: "watermelon" },
  { id: 12, name: "Cantaloupe", value: "cantaloupe" },
  { id: 13, name: "Kiwi", value: "kiwi" },
  { id: 14, name: "Cherry", value: "cherry" },
  { id: 15, name: "Pear", value: "pear" },
  { id: 16, name: "Peach", value: "peach" },
  { id: 17, name: "Plum", value: "plum" },
  { id: 18, name: "Lemon", value: "lemon" },
  { id: 19, name: "Lime", value: "lime" },
  { id: 20, name: "Coconut", value: "coconut" },
  { id: 21, name: "Pomegranate", value: "pomegranate" },
  { id: 22, name: "Guava", value: "guava" },
  { id: 23, name: "Lychee", value: "lychee" },
  { id: 24, name: "Fig", value: "fig" },
  { id: 25, name: "Dates", value: "dates" },
  { id: 26, name: "Dragon Fruit", value: "dragon_fruit" },
  { id: 27, name: "Starfruit", value: "starfruit" },
  { id: 28, name: "Raspberry", value: "raspberry" },
  { id: 29, name: "Mulberry", value: "mulberry" },
  { id: 30, name: "Tangerine", value: "tangerine" },
  { id: 31, name: "Jackfruit", value: "jackfruit" },
  { id: 32, name: "Passion Fruit", value: "passion_fruit" },
  { id: 33, name: "Apricot", value: "apricot" },
  { id: 34, name: "Cranberry", value: "cranberry" },
  { id: 35, name: "Rambutan", value: "rambutan" },
  { id: 36, name: "Durian", value: "durian" },
  { id: 37, name: "Persimmon", value: "persimmon" },
  { id: 38, name: "Soursop", value: "soursop" },
  { id: 39, name: "Custard Apple", value: "custard_apple" },
  { id: 40, name: "Sapota", value: "sapota" },
  { id: 41, name: "Tamarind", value: "tamarind" },
  { id: 42, name: "Gooseberry", value: "gooseberry" },
  { id: 43, name: "Nectarine", value: "nectarine" },
  { id: 44, name: "Breadfruit", value: "breadfruit" },
  { id: 45, name: "Clementine", value: "clementine" },
  { id: 46, name: "Longan", value: "longan" },
  { id: 47, name: "Jujube", value: "jujube" },
  { id: 48, name: "Pomelo", value: "pomelo" },
  { id: 49, name: "Mandarin", value: "mandarin" },
  { id: 50, name: "Boysenberry", value: "boysenberry" }
];
